title: "CHIRPS-2.0 global daily"
description: >
  Climate Hazards Group InfraRed Precipitation with Station data (CHIRPS)
recipes:
  - id: "chirps-global-daily"
    object: "recipe:recipe"
provenance:
  providers:
    - name: "Julius"
      description: "Just a guy testing some recipes. Nothing to see here."
      roles:
        - producer
        - licensor
  license: "Just a Test"
maintainers:
  - name: "Julius Busecke"
    orcid: "0000-0001-8571-865X"
    github: jbusecke
